<?php
date_default_timezone_set('America/Costa_Rica');

//configuracion
$gatewayUrl = $this->helper("paymentgateway")->getPaymentmethodPaymentgatewayurl();
$key = $this->helper("paymentgateway")->getKey();
$keyId = $this->helper("paymentgateway")->getKeyId();
$processorId = $this->helper("paymentgateway")->getProcessorId();

$order = new Mage_Sales_Model_Order(); //object to get all order information
$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$order->loadByIncrementId($orderId);

//Quita el punto decimal del monto
$amount = number_format($order->getBaseGrandTotal(),2);
$time = time();
$hash = md5("$orderId|$amount|$time|$key");

$locale = Mage::app()->getLocale()->getLocaleCode();

$txtTitle = 'Informaci&oacute;n de su Tarjeta de Cr&eacute;dito';
$txtSubtitle = 'Por favor ingrese los datos de su tarjeta.';
$txtSubmit = 'Enviar';
$txtCreditCardNumber = 'N&uacute;mero en la Tarjeta';
$txtExpiration = 'Fecha de Expiraci&oacute;n';
$txtCvv = 'C&oacute;digo de Seguridad';
if($locale=="en_US")
{
    $txtTitle = 'Credit Card Information';
    $txtSubtitle = 'Please enter your card information.';
    $txtSubmit = 'Submit';
    $txtCreditCardNumber = 'Card Number';
    $txtExpiration = 'Expiration Date';
    $txtCvv = 'Security Code';
}

?>
<style>
    .logos{
        float:right;
        margin-right: 50%;
    }
    .logos #mastercard_logo{

    }
    .logos #visa_logo{
        width: 116px;
    }
</style>
<div class='dashboard mid-width'>
    <h1><?php echo $txtTitle ?></h1>
    <br/>
    <p><?php echo $txtSubtitle ?></p>
    <div class="logos">
        <img src="http://dkoko.com/skin/frontend/dkoko/default/img/master_card_logo.gif" alt="MasterCard SecureCode" id="mastercard_logo">
        <img src="http://dkoko.com/skin/frontend/dkoko/default/img/visa_logo.jpg" alt="Verified by VISA" id="visa_logo">
    </div>
    <form name="CredomaticPost" method="post" action="<?php echo $gatewayUrl; ?>">
        <input type="hidden" name="amount" id="amount" value="<?php echo $amount ?>">
        <input type="hidden" name="hash" id="hash" value="<?php echo $hash ?>">
        <input type="hidden" name="time" id="time" value="<?php echo $time ?>">
        <input type="hidden" name="key_id" id="key_id" value="<?php echo $keyId; ?>">
        <input type="hidden" name="processor_id" id="processor_id" value="<?php echo $processorId; ?>">
        <input type="hidden" name="orderid" id="orderid" value="<?php echo $orderId; ?>">
        <label for="ccnumber"><?php echo $txtCreditCardNumber ?></label>
        <input type="text" name="ccnumber" id="ccnumber" value="" style="width:auto" size='16' required>
        <label for="ccexp"><?php echo $txtExpiration ?></label>
        <input type="text" name="ccexp" id="ccexp" value="" style="width:auto" size="5" placeholder="MMYY" required>
        <label for="cvv"><?php echo $txtCvv ?></label>
        <input type="password" name="cvv" id="cvv" value="" style="width:auto" size="4" required>
        <input type="hidden" name="type" id="type" value="sale">
        <input type="hidden" name="redirect" id="redirect" value="http://dkoko.com/payget/paygateway/success">
        <input type="submit" value="<?php echo $txtSubmit ?>" class="button btn-l">
    </form>
</div>